name: main

on: [push]

jobs:
  main:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Cache things
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}
        path: |
          ~/.cache
          ~/.poetry
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        curl -sSL https://install.python-poetry.org | python3 -
        export POETRY_HOME=$HOME/.poetry/bin
        echo "$POETRY_HOME" >>$GITHUB_PATH
        export PATH="$POETRY_HOME:$PATH"
        poetry install --with=dev
    - name: Run pre-commit
      run: |
        poetry run pre-commit run -av
    - name: test executable help output
      run: |
        ./tests/test_binaries_help_output.sh
#    - name: run pytest
#      run: |
#        poetry run pytest -vv
