name: main

on: [push]

jobs:
  main:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache things
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}
        path: |
          ~/.cache
          ~/.poetry
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # enable once I've convinced cknowles to use poetry
        # curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
        # export POETRY_HOME=$HOME/.poetry/bin
        # echo "$POETRY_HOME" >>$GITHUB_PATH
        # export PATH="$POETRY_HOME:$PATH"
        # poetry install
        pip install -r requirements.txt
        pip install -U pre-commit
    - name: Run pre-commit
      run: |
        pre-commit run -av
